# Generated by Django 5.0.3 on 2024-03-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorhospitalmapping',
            name='user',
        ),
        migrations.AddField(
            model_name='doctorhospitalmapping',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
