# Generated by Django 5.0.3 on 2024-03-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrmanagement', '0002_remove_doctorhospitalmapping_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitallist',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hospitallist',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
